//Films types
export const FILMS_REQUEST = "FILMS_REQUEST";
export const FILMS_RECEIVE = "FILMS_RECEIVE";
export const FILMS_CHANGE_SORTBY = "FILMS_CHANGE_SORTBY";
export const FILMS_CHANGE_SEARCHBY = "FILMS_CHANGE_SEARCHBY";
export const FILMS_CHANGE_SEARCH_INPUT_VALUE =
  "FILMS_CHANGE_SEARCH_INPUT_VALUE";
